FROM golang:1.23-alpine3.19

RUN go install github.com/a-h/templ/cmd/templ@v0.3.819
RUN go install github.com/bokwoon95/wgo@latest

WORKDIR /app

COPY . .

RUN go mod download

CMD ["wgo", "-file=.go", "-file=.templ", "-xfile=_templ.go", "templ" ,"generate" ,"::", "go" ,"run" ,"main.go"]
