FROM golang:1.23-alpine3.19

RUN go install github.com/air-verse/air@v1.52.3
RUN go install github.com/a-h/templ/cmd/templ@latest

WORKDIR /app

COPY . .

RUN go mod download

CMD ["air", "-c", ".air.toml" , "-d"]
