services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080-8081:8080"
    environment:
      - ENV=production

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - $./caddy/Caddyfile.prod:/etc/caddy/Caddyfile