FROM golang:1.25-alpine

RUN apk add --no-cache ca-certificates

RUN go install github.com/a-h/templ/cmd/templ@v0.3.1001
RUN go install github.com/bokwoon95/wgo@v0.6.3

WORKDIR /app

COPY . .

RUN go mod download

CMD ["wgo", "-file=.go", "-file=.templ", "-xfile=_templ.go", "--", "templ" ,"generate" ,"::", "go" ,"run" ,"./cmd/personal-website/main.go"]
