// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package homepage

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LandingPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-screen pt-24\"><div class=\"h-full flex flex-col justify-center items-center py-10 pb-14\"><div class=\"flex-1 flex flex-col gap-2\"><h1 class=\"text-5xl sm:text-6xl lg:text-7xl font-semibold mt-[50%]\">Alex Lupatsiy</h1><h2 class=\"text-3xl lg:text-4xl font-medium \">Software Engineer</h2></div><div class=\"flex shadow-md shadow-[#4CB8C4] hover:shadow-[#3CD3AD] hover:-translate-y-0.5 transition-all duration-700 px-6 py-4  justify-center gap-4 items-center rounded-3xl overflow-hidden bg-white\"><p class=\"text-xl\">Get in touch!</p><button class=\"btn-grad px-5 py-3 rounded-2xl shadow-inner text-xl\">Email me</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
